# Generated by Django 5.1.1 on 2024-09-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='wins',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='match_history',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='match_history',
            field=models.ManyToManyField(blank=True, to='main_app.matchhistory'),
        ),
    ]
