# Generated by Django 5.1.1 on 2024-09-22 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_tournament_participants_tournament_user_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='user_ids',
        ),
        migrations.AddField(
            model_name='tournament',
            name='user_ids',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
