# Generated by Django 5.1.1 on 2024-09-22 11:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_tournament_user_ids_tournament_user_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='user_ids',
        ),
        migrations.AddField(
            model_name='tournament',
            name='user_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
