# Generated by Django 5.1.1 on 2024-09-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_tournament_user_ids_tournament_user_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
