# Generated by Django 5.1.1 on 2024-09-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_tournament_user_ids_tournament_winners_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchhistory',
            name='player2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='matchhistory',
            name='winner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
