# Generated by Django 5.1.2 on 2024-10-22 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_friend_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='winners_order',
        ),
    ]
