# Generated by Django 5.1.2 on 2024-10-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_remove_tournament_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertwofactorauthdata',
            name='app_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertwofactorauthdata',
            name='email_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertwofactorauthdata',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='usertwofactorauthdata',
            name='sms_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
