# Generated by Django 5.1.2 on 2024-11-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_usertwofactorauthdata_app_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='oauth',
            field=models.BooleanField(default=False),
        ),
    ]
