# Generated by Django 5.1.2 on 2024-11-02 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_userprofile_oauth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='oauth',
        ),
    ]
